[devshell]
name = "pico-print"

### Help/intro text
### While called "motd", I'd say this as a good place to introduce the project
### and write some short notes on usage. This is displayed in the terminal when
### entering the devshell (either through `nix develop` or using direnv).

### Note that you can both use replacement strings for terminal colors and formatting + include output from a command as below (where we show the menu of commands).

# motd = """
# {bold}{106}My Awesome Project{reset}
# 
# This project does a bit of this and that. To use it you should first run the command "blargh" and then all your wishes come true.
# 
# $(type -p menu &>/dev/null && menu)
# """

### Add tools to be brought into your shell automatically.
 packages = [ "esptool", "micropython", "adafruit-ampy", "picocom", "screen", "elvish" ]

### Commands

[[commands]]
name = "esp"
help = "alias for esptool"
category = "tools"
command = "esptool.py $@"

[[commands]]
name = "build"
help = "run the buildscript"
category = "commands"
command = "scripts/build"

[[commands]]
name = "install"
help = "install to the attached micropython device"
category = "commands"
command = "scripts/install"

[[commands]]
name = "repl"
help = "connect to the repl of the attached device"
category = "commands"
command = "picocom $DEVICE -b$BAUD"

[[env]]
name = "DEVICE"
value = "/dev/ttyUSB0"

[[env]]
name = "BAUD"
value = "115200"
