#!/usr/bin/env bash

rm -rf dist
mkdir -p dist

echo "=== Copying micropython code..."
cp -r src/* dist/

echo "=== Building Svelte app..."
cd svelte
npm run build
cd ../

echo "=== Copying Svelte app..."
cp -r svelte/public dist/
echo "=== Done!"
